name: Verify signed commits 
on: pull_request_target

jobs:
  check-signed-commits:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Verify signed commits
        uses: 1Password/check-signed-commits-action@v1