name: PR Lint

on:
  pull_request:
    # By default, a workflow only runs when a pull_request's activity type is opened, synchronize, or reopened. We
    # explicity override here so that PR titles are re-linted when the PR text content is edited.
    #
    # Possible values: https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
    types: [opened, edited, reopened, synchronize]

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: yakupafsin/WordpressMobileApp/.github/actions/setupNode@main

      - name: Lint JavaScript and Typescript with ESLint
        run: npx eslint --fix .

      - name: Verify there's no Prettier diff
        run: |
          npm run prettier -- --loglevel silent
          if ! git diff --name-only --exit-code; then
            # shellcheck disable=SC2016
            echo 'Error: Prettier diff detected! Please run `npm run prettier` and commit the changes.'
            exit 1
          fi